// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef XRESIZE_IP_H
#define XRESIZE_IP_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xresize_ip_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Axilites_BaseAddress;
} XResize_ip_Config;
#endif

typedef struct {
    u32 Axilites_BaseAddress;
    u32 IsReady;
} XResize_ip;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XResize_ip_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XResize_ip_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XResize_ip_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XResize_ip_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XResize_ip_Initialize(XResize_ip *InstancePtr, u16 DeviceId);
XResize_ip_Config* XResize_ip_LookupConfig(u16 DeviceId);
int XResize_ip_CfgInitialize(XResize_ip *InstancePtr, XResize_ip_Config *ConfigPtr);
#else
int XResize_ip_Initialize(XResize_ip *InstancePtr, const char* InstanceName);
int XResize_ip_Release(XResize_ip *InstancePtr);
#endif

void XResize_ip_Start(XResize_ip *InstancePtr);
u32 XResize_ip_IsDone(XResize_ip *InstancePtr);
u32 XResize_ip_IsIdle(XResize_ip *InstancePtr);
u32 XResize_ip_IsReady(XResize_ip *InstancePtr);
void XResize_ip_EnableAutoRestart(XResize_ip *InstancePtr);
void XResize_ip_DisableAutoRestart(XResize_ip *InstancePtr);

void XResize_ip_Set_src_height(XResize_ip *InstancePtr, u32 Data);
u32 XResize_ip_Get_src_height(XResize_ip *InstancePtr);
void XResize_ip_Set_src_width(XResize_ip *InstancePtr, u32 Data);
u32 XResize_ip_Get_src_width(XResize_ip *InstancePtr);
void XResize_ip_Set_dst_height(XResize_ip *InstancePtr, u32 Data);
u32 XResize_ip_Get_dst_height(XResize_ip *InstancePtr);
void XResize_ip_Set_dst_width(XResize_ip *InstancePtr, u32 Data);
u32 XResize_ip_Get_dst_width(XResize_ip *InstancePtr);

void XResize_ip_InterruptGlobalEnable(XResize_ip *InstancePtr);
void XResize_ip_InterruptGlobalDisable(XResize_ip *InstancePtr);
void XResize_ip_InterruptEnable(XResize_ip *InstancePtr, u32 Mask);
void XResize_ip_InterruptDisable(XResize_ip *InstancePtr, u32 Mask);
void XResize_ip_InterruptClear(XResize_ip *InstancePtr, u32 Mask);
u32 XResize_ip_InterruptGetEnabled(XResize_ip *InstancePtr);
u32 XResize_ip_InterruptGetStatus(XResize_ip *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
