#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2018.2 (64-bit)
#
# Filename    : system.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Fri Jul 26 18:00:12 +0800 2019
# SW Build 2258646 on Thu Jun 14 20:03:12 MDT 2018
#
# Copyright 1986-2018 Xilinx, Inc. All Rights Reserved. 
#
# usage: system.sh [-help]
# usage: system.sh [-lib_map_path]
# usage: system.sh [-noclean_files]
# usage: system.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'system.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64"
vhdlan_opts="-full64"
vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xilinx_vip xil_defaultlib xpm axi_infrastructure_v1_1_0 smartconnect_v1_0 axi_protocol_checker_v2_0_3 axi_vip_v1_1_3 processing_system7_vip_v1_0_5 lib_cdc_v1_0_2 proc_sys_reset_v5_0_12 xlconstant_v1_1_5 lib_pkg_v1_0_2 fifo_generator_v13_2_2 lib_fifo_v1_0_11 blk_mem_gen_v8_4_1 lib_bmg_v1_0_10 lib_srl_fifo_v1_0_2 axi_datamover_v5_1_19 axi_vdma_v6_3_5 xlconcat_v2_1_1 axi_lite_ipif_v3_0_4 axi_intc_v4_1_11 v_tc_v6_1_12 v_vid_in_axi4s_v4_0_8 v_axi4s_vid_out_v4_0_9 v_demosaic_v1_0_3 generic_baseblocks_v2_1_0 axi_register_slice_v2_1_17 axi_data_fifo_v2_1_16 axi_crossbar_v2_1_18 axis_infrastructure_v1_1_0 axis_register_slice_v1_1_17 axis_subset_converter_v1_1_17 axi_protocol_converter_v2_1_17)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "system.sh - Script generated by export_simulation (Vivado v2018.2 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xilinx_vip $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b65a" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/0ab1/hdl" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "C:/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
    "C:/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
    "C:/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
    "C:/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
    "C:/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
    "C:/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
    "C:/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/axi_vip_if.sv" \
    "C:/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/clk_vip_if.sv" \
    "C:/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b65a" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/0ab1/hdl" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "C:/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "C:/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
    "C:/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "C:/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b65a" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/0ab1/hdl" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b65a" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/0ab1/hdl" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/5bb9/hdl/sc_util_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_protocol_checker_v2_0_3 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b65a" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/0ab1/hdl" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/03a9/hdl/axi_protocol_checker_v2_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_vip_v1_1_3 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b65a" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/0ab1/hdl" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b9a8/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work processing_system7_vip_v1_0_5 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b65a" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/0ab1/hdl" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/70fd/hdl/processing_system7_vip_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b65a" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/0ab1/hdl" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_processing_system7_0_0/sim/system_processing_system7_0_0.v" \
    "$ref_dir/../../../bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0_clk_wiz.v" \
    "$ref_dir/../../../bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work proc_sys_reset_v5_0_12 $vhdlan_opts \
    "$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/f86a/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_rst_clk_wiz_0_150M_0/sim/system_rst_clk_wiz_0_150M_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b65a" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/0ab1/hdl" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_1/bd_0/sim/bd_8422.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b65a" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/0ab1/hdl" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/5160/hdl/sc_axi2sc_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b65a" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/0ab1/hdl" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_1/bd_0/ip/ip_10/sim/bd_8422_s00a2s_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_1/bd_0/ip/ip_16/sim/bd_8422_s01a2s_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_1/bd_0/ip/ip_23/sim/bd_8422_s02a2s_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_1/bd_0/ip/ip_29/sim/bd_8422_s03a2s_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b65a" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/0ab1/hdl" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/acc2/hdl/sc_sc2axi_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b65a" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/0ab1/hdl" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_1/bd_0/ip/ip_33/sim/bd_8422_m00s2a_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b65a" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/0ab1/hdl" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/28cb/hdl/sc_exit_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b65a" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/0ab1/hdl" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_1/bd_0/ip/ip_39/sim/bd_8422_m00e_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b65a" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/0ab1/hdl" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/f90c/hdl/sc_node_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b65a" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/0ab1/hdl" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_1/bd_0/ip/ip_34/sim/bd_8422_m00arn_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_1/bd_0/ip/ip_35/sim/bd_8422_m00rn_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_1/bd_0/ip/ip_36/sim/bd_8422_m00awn_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_1/bd_0/ip/ip_37/sim/bd_8422_m00wn_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_1/bd_0/ip/ip_38/sim/bd_8422_m00bn_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_1/bd_0/ip/ip_30/sim/bd_8422_sawn_1.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_1/bd_0/ip/ip_31/sim/bd_8422_swn_1.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_1/bd_0/ip/ip_32/sim/bd_8422_sbn_1.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b65a" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/0ab1/hdl" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/afa8/hdl/sc_mmu_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b65a" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/0ab1/hdl" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_1/bd_0/ip/ip_26/sim/bd_8422_s03mmu_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b65a" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/0ab1/hdl" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/4521/hdl/sc_transaction_regulator_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b65a" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/0ab1/hdl" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_1/bd_0/ip/ip_27/sim/bd_8422_s03tr_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b65a" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/0ab1/hdl" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/d1fc/hdl/sc_si_converter_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b65a" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/0ab1/hdl" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_1/bd_0/ip/ip_28/sim/bd_8422_s03sic_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_1/bd_0/ip/ip_24/sim/bd_8422_sarn_1.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_1/bd_0/ip/ip_25/sim/bd_8422_srn_1.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_1/bd_0/ip/ip_20/sim/bd_8422_s02mmu_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_1/bd_0/ip/ip_21/sim/bd_8422_s02tr_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_1/bd_0/ip/ip_22/sim/bd_8422_s02sic_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_1/bd_0/ip/ip_17/sim/bd_8422_sawn_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_1/bd_0/ip/ip_18/sim/bd_8422_swn_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_1/bd_0/ip/ip_19/sim/bd_8422_sbn_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_1/bd_0/ip/ip_13/sim/bd_8422_s01mmu_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_1/bd_0/ip/ip_14/sim/bd_8422_s01tr_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_1/bd_0/ip/ip_15/sim/bd_8422_s01sic_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_1/bd_0/ip/ip_11/sim/bd_8422_sarn_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_1/bd_0/ip/ip_12/sim/bd_8422_srn_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_1/bd_0/ip/ip_7/sim/bd_8422_s00mmu_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_1/bd_0/ip/ip_8/sim/bd_8422_s00tr_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_1/bd_0/ip/ip_9/sim/bd_8422_s00sic_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b65a" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/0ab1/hdl" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/4e7b/hdl/sc_switchboard_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b65a" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/0ab1/hdl" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_1/bd_0/ip/ip_2/sim/bd_8422_arsw_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_1/bd_0/ip/ip_3/sim/bd_8422_rsw_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_1/bd_0/ip/ip_4/sim/bd_8422_awsw_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_1/bd_0/ip/ip_5/sim/bd_8422_wsw_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_1/bd_0/ip/ip_6/sim/bd_8422_bsw_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlconstant_v1_1_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b65a" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/0ab1/hdl" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/f1c3/hdl/xlconstant_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b65a" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/0ab1/hdl" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_1/bd_0/ip/ip_0/sim/bd_8422_one_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_1/bd_0/ip/ip_1/sim/bd_8422_psr_aclk_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b65a" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/0ab1/hdl" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_1/sim/system_axi_smc_1.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_pkg_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/0513/hdl/lib_pkg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_2 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b65a" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/0ab1/hdl" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/7aff/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_2_2 $vhdlan_opts \
    "$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/7aff/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_2 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b65a" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/0ab1/hdl" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/7aff/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_fifo_v1_0_11 $vhdlan_opts \
    "$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/6078/hdl/lib_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work blk_mem_gen_v8_4_1 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b65a" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/0ab1/hdl" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/67d8/simulation/blk_mem_gen_v8_4.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_bmg_v1_0_10 $vhdlan_opts \
    "$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/9340/hdl/lib_bmg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_srl_fifo_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/51ce/hdl/lib_srl_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_datamover_v5_1_19 $vhdlan_opts \
    "$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/ec8a/hdl/axi_datamover_v5_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_vdma_v6_3_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b65a" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/0ab1/hdl" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b37e/hdl/axi_vdma_v6_3_rfs.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_vdma_v6_3_5 $vhdlan_opts \
    "$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b37e/hdl/axi_vdma_v6_3_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_axi_vdma_1_0/sim/system_axi_vdma_1_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xlconcat_v2_1_1 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b65a" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/0ab1/hdl" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/2f66/hdl/xlconcat_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b65a" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/0ab1/hdl" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_xlconcat_0_0/sim/system_xlconcat_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_lite_ipif_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/cced/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_intc_v4_1_11 $vhdlan_opts \
    "$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/2fec/hdl/axi_intc_v4_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_axi_intc_0_0/sim/system_axi_intc_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b65a" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/0ab1/hdl" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/9097/src/mmcme2_drp.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/9097/src/axi_dynclk_S00_AXI.vhd" \
    "$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/9097/src/axi_dynclk.vhd" \
    "$ref_dir/../../../bd/system/ip/system_axi_dynclk_0_0/sim/system_axi_dynclk_0_0.vhd" \
    "$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/bd5a/src/ClockGen.vhd" \
    "$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/bd5a/src/SyncAsync.vhd" \
    "$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/bd5a/src/SyncAsyncReset.vhd" \
    "$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/bd5a/src/DVI_Constants.vhd" \
    "$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/bd5a/src/OutputSERDES.vhd" \
    "$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/bd5a/src/TMDS_Encoder.vhd" \
    "$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/bd5a/src/rgb2dvi.vhd" \
    "$ref_dir/../../../bd/system/ip/system_rgb2dvi_0_0/sim/system_rgb2dvi_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work v_tc_v6_1_12 $vhdlan_opts \
    "$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/6694/hdl/v_tc_v6_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_v_tc_0_0/sim/system_v_tc_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work v_vid_in_axi4s_v4_0_8 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b65a" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/0ab1/hdl" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/d987/hdl/v_vid_in_axi4s_v4_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work v_axi4s_vid_out_v4_0_9 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b65a" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/0ab1/hdl" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/9a07/hdl/v_axi4s_vid_out_v4_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b65a" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/0ab1/hdl" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_v_axi4s_vid_out_0_1/sim/system_v_axi4s_vid_out_0_1.v" \
    "$ref_dir/../../../bd/system/ip/system_xlconstant_0_0/sim/system_xlconstant_0_0.v" \
    "$ref_dir/../../../bd/system/ip/system_xlconstant_0_1/sim/system_xlconstant_0_1.v" \
    "$ref_dir/../../../bd/system/ip/system_v_vid_in_axi4s_0_0/sim/system_v_vid_in_axi4s_0_0.v" \
    "$ref_dir/../../../bd/system/ip/system_v_demosaic_0_0/hdl/verilog/system_v_demosaic_0_0_AXIvideo2MultiBayer2.v" \
    "$ref_dir/../../../bd/system/ip/system_v_demosaic_0_0/hdl/verilog/system_v_demosaic_0_0_Debayer.v" \
    "$ref_dir/../../../bd/system/ip/system_v_demosaic_0_0/hdl/verilog/system_v_demosaic_0_0_DebayerG.v" \
    "$ref_dir/../../../bd/system/ip/system_v_demosaic_0_0/hdl/verilog/system_v_demosaic_0_0_DebayerG_DIV1_TABLE.v" \
    "$ref_dir/../../../bd/system/ip/system_v_demosaic_0_0/hdl/verilog/system_v_demosaic_0_0_DebayerG_DIV2_TABLE.v" \
    "$ref_dir/../../../bd/system/ip/system_v_demosaic_0_0/hdl/verilog/system_v_demosaic_0_0_DebayerG_linebuf_bkb.v" \
    "$ref_dir/../../../bd/system/ip/system_v_demosaic_0_0/hdl/verilog/system_v_demosaic_0_0_DebayerRandBatG.v" \
    "$ref_dir/../../../bd/system/ip/system_v_demosaic_0_0/hdl/verilog/system_v_demosaic_0_0_DebayerRatBorBatR.v" \
    "$ref_dir/../../../bd/system/ip/system_v_demosaic_0_0/hdl/verilog/system_v_demosaic_0_0_DebayerRatBorBatRjbC.v" \
    "$ref_dir/../../../bd/system/ip/system_v_demosaic_0_0/hdl/verilog/system_v_demosaic_0_0_fifo_w8_d2_A.v" \
    "$ref_dir/../../../bd/system/ip/system_v_demosaic_0_0/hdl/verilog/system_v_demosaic_0_0_fifo_w8_d2_A_x.v" \
    "$ref_dir/../../../bd/system/ip/system_v_demosaic_0_0/hdl/verilog/system_v_demosaic_0_0_fifo_w16_d2_A.v" \
    "$ref_dir/../../../bd/system/ip/system_v_demosaic_0_0/hdl/verilog/system_v_demosaic_0_0_fifo_w16_d2_A_x.v" \
    "$ref_dir/../../../bd/system/ip/system_v_demosaic_0_0/hdl/verilog/system_v_demosaic_0_0_MultiPixStream2AXIvi.v" \
    "$ref_dir/../../../bd/system/ip/system_v_demosaic_0_0/hdl/verilog/system_v_demosaic_0_0_reg_unsigned_short_s.v" \
    "$ref_dir/../../../bd/system/ip/system_v_demosaic_0_0/hdl/verilog/system_v_demosaic_0_0_v_demosaic_CTRL_s_axi.v" \
    "$ref_dir/../../../bd/system/ip/system_v_demosaic_0_0/hdl/verilog/system_v_demosaic_0_0_v_demosaic_mac_muibs.v" \
    "$ref_dir/../../../bd/system/ip/system_v_demosaic_0_0/hdl/verilog/system_v_demosaic_0_0_v_demosaic_mul_mug8j.v" \
    "$ref_dir/../../../bd/system/ip/system_v_demosaic_0_0/hdl/verilog/system_v_demosaic_0_0_v_demosaic_mul_muhbi.v" \
    "$ref_dir/../../../bd/system/ip/system_v_demosaic_0_0/hdl/verilog/system_v_demosaic_0_0_v_demosaic_mux_32lbW.v" \
    "$ref_dir/../../../bd/system/ip/system_v_demosaic_0_0/hdl/verilog/system_v_demosaic_0_0_v_demosaic_mux_53fYi.v" \
    "$ref_dir/../../../bd/system/ip/system_v_demosaic_0_0/hdl/verilog/system_v_demosaic_0_0_ZipperRemoval.v" \
    "$ref_dir/../../../bd/system/ip/system_v_demosaic_0_0/hdl/verilog/system_v_demosaic_0_0_v_demosaic.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work v_demosaic_v1_0_3 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b65a" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/0ab1/hdl" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ip/system_v_demosaic_0_0/hdl/v_demosaic_v1_0_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b65a" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/0ab1/hdl" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_v_demosaic_0_0/sim/system_v_demosaic_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_axi_vdma_0_0/sim/system_axi_vdma_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work generic_baseblocks_v2_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b65a" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/0ab1/hdl" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_17 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b65a" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/0ab1/hdl" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/6020/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_data_fifo_v2_1_16 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b65a" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/0ab1/hdl" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/247d/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_crossbar_v2_1_18 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b65a" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/0ab1/hdl" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/15a3/hdl/axi_crossbar_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b65a" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/0ab1/hdl" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_xbar_0/sim/system_xbar_0.v" \
    "$ref_dir/../../../bd/system/ip/system_video_divide_0_0/sim/system_video_divide_0_0.v" \
    "$ref_dir/../../../bd/system/ip/system_video_concat_0_0/sim/system_video_concat_0_0.v" \
    "$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/9896/hdl/verilog/inner_ctrl_AXILiteS_s_axi.v" \
    "$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/9896/hdl/verilog/inner_ctrl.v" \
    "$ref_dir/../../../bd/system/ip/system_inner_ctrl_0_0/sim/system_inner_ctrl_0_0.v" \
    "$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/facd/hdl/verilog/AXIvideo2xfMat.v" \
    "$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/facd/hdl/verilog/Block_Mat_exit101_pr.v" \
    "$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/facd/hdl/verilog/fifo_w8_d1_A.v" \
    "$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/facd/hdl/verilog/fifo_w8_d2_A.v" \
    "$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/facd/hdl/verilog/fifo_w32_d2_A.v" \
    "$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/facd/hdl/verilog/fifo_w32_d2_A_x.v" \
    "$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/facd/hdl/verilog/fifo_w32_d3_A.v" \
    "$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/facd/hdl/verilog/fifo_w32_d3_A_x.v" \
    "$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/facd/hdl/verilog/fifo_w32_d4_A.v" \
    "$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/facd/hdl/verilog/Sobel.v" \
    "$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/facd/hdl/verilog/sobel_accel.v" \
    "$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/facd/hdl/verilog/Sobel_Block_xFSobelF.v" \
    "$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/facd/hdl/verilog/sobel_ip_AXILiteS_s_axi.v" \
    "$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/facd/hdl/verilog/sobel_ip_mux_32_8eOg.v" \
    "$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/facd/hdl/verilog/Sobel_Loop_1_proc616.v" \
    "$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/facd/hdl/verilog/Sobel_Loop_2_proc62.v" \
    "$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/facd/hdl/verilog/start_for_sobel_ahbi.v" \
    "$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/facd/hdl/verilog/start_for_Sobel_BfYi.v" \
    "$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/facd/hdl/verilog/start_for_Sobel_Lg8j.v" \
    "$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/facd/hdl/verilog/start_for_xfMat2Aibs.v" \
    "$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/facd/hdl/verilog/start_for_xfMat2AjbC.v" \
    "$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/facd/hdl/verilog/xFGradientX3x3_0_0_s.v" \
    "$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/facd/hdl/verilog/xFGradientY3x3_0_0_s.v" \
    "$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/facd/hdl/verilog/xfMat2AXIvideo.v" \
    "$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/facd/hdl/verilog/xfMat2AXIvideo57.v" \
    "$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/facd/hdl/verilog/xFSobel3x3.v" \
    "$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/facd/hdl/verilog/xFSobelFilter3x3.v" \
    "$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/facd/hdl/verilog/xFSobelFilter3x3_bkb.v" \
    "$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/facd/hdl/verilog/sobel_ip.v" \
    "$ref_dir/../../../bd/system/ip/system_sobel_ip_0_1/sim/system_sobel_ip_0_1.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axis_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b65a" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/0ab1/hdl" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/0ab1/hdl/axis_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axis_register_slice_v1_1_17 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b65a" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/0ab1/hdl" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/15d7/hdl/axis_register_slice_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b65a" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/0ab1/hdl" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_axis_subset_converter_0_10/hdl/tdata_system_axis_subset_converter_0_10.v" \
    "$ref_dir/../../../bd/system/ip/system_axis_subset_converter_0_10/hdl/tuser_system_axis_subset_converter_0_10.v" \
    "$ref_dir/../../../bd/system/ip/system_axis_subset_converter_0_10/hdl/tstrb_system_axis_subset_converter_0_10.v" \
    "$ref_dir/../../../bd/system/ip/system_axis_subset_converter_0_10/hdl/tkeep_system_axis_subset_converter_0_10.v" \
    "$ref_dir/../../../bd/system/ip/system_axis_subset_converter_0_10/hdl/tid_system_axis_subset_converter_0_10.v" \
    "$ref_dir/../../../bd/system/ip/system_axis_subset_converter_0_10/hdl/tdest_system_axis_subset_converter_0_10.v" \
    "$ref_dir/../../../bd/system/ip/system_axis_subset_converter_0_10/hdl/tlast_system_axis_subset_converter_0_10.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axis_subset_converter_v1_1_17 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b65a" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/0ab1/hdl" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/5a7d/hdl/axis_subset_converter_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b65a" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/0ab1/hdl" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_axis_subset_converter_0_10/hdl/top_system_axis_subset_converter_0_10.v" \
    "$ref_dir/../../../bd/system/ip/system_axis_subset_converter_0_10/sim/system_axis_subset_converter_0_10.v" \
    "$ref_dir/../../../bd/system/ip/system_axis_subset_converter_0_11/hdl/tdata_system_axis_subset_converter_0_11.v" \
    "$ref_dir/../../../bd/system/ip/system_axis_subset_converter_0_11/hdl/tuser_system_axis_subset_converter_0_11.v" \
    "$ref_dir/../../../bd/system/ip/system_axis_subset_converter_0_11/hdl/tstrb_system_axis_subset_converter_0_11.v" \
    "$ref_dir/../../../bd/system/ip/system_axis_subset_converter_0_11/hdl/tkeep_system_axis_subset_converter_0_11.v" \
    "$ref_dir/../../../bd/system/ip/system_axis_subset_converter_0_11/hdl/tid_system_axis_subset_converter_0_11.v" \
    "$ref_dir/../../../bd/system/ip/system_axis_subset_converter_0_11/hdl/tdest_system_axis_subset_converter_0_11.v" \
    "$ref_dir/../../../bd/system/ip/system_axis_subset_converter_0_11/hdl/tlast_system_axis_subset_converter_0_11.v" \
    "$ref_dir/../../../bd/system/ip/system_axis_subset_converter_0_11/hdl/top_system_axis_subset_converter_0_11.v" \
    "$ref_dir/../../../bd/system/ip/system_axis_subset_converter_0_11/sim/system_axis_subset_converter_0_11.v" \
    "$ref_dir/../../../bd/system/ip/system_axis_subset_converter_0_12/hdl/tdata_system_axis_subset_converter_0_12.v" \
    "$ref_dir/../../../bd/system/ip/system_axis_subset_converter_0_12/hdl/tuser_system_axis_subset_converter_0_12.v" \
    "$ref_dir/../../../bd/system/ip/system_axis_subset_converter_0_12/hdl/tstrb_system_axis_subset_converter_0_12.v" \
    "$ref_dir/../../../bd/system/ip/system_axis_subset_converter_0_12/hdl/tkeep_system_axis_subset_converter_0_12.v" \
    "$ref_dir/../../../bd/system/ip/system_axis_subset_converter_0_12/hdl/tid_system_axis_subset_converter_0_12.v" \
    "$ref_dir/../../../bd/system/ip/system_axis_subset_converter_0_12/hdl/tdest_system_axis_subset_converter_0_12.v" \
    "$ref_dir/../../../bd/system/ip/system_axis_subset_converter_0_12/hdl/tlast_system_axis_subset_converter_0_12.v" \
    "$ref_dir/../../../bd/system/ip/system_axis_subset_converter_0_12/hdl/top_system_axis_subset_converter_0_12.v" \
    "$ref_dir/../../../bd/system/ip/system_axis_subset_converter_0_12/sim/system_axis_subset_converter_0_12.v" \
    "$ref_dir/../../../bd/system/ip/system_axis_subset_converter_0_13/hdl/tdata_system_axis_subset_converter_0_13.v" \
    "$ref_dir/../../../bd/system/ip/system_axis_subset_converter_0_13/hdl/tuser_system_axis_subset_converter_0_13.v" \
    "$ref_dir/../../../bd/system/ip/system_axis_subset_converter_0_13/hdl/tstrb_system_axis_subset_converter_0_13.v" \
    "$ref_dir/../../../bd/system/ip/system_axis_subset_converter_0_13/hdl/tkeep_system_axis_subset_converter_0_13.v" \
    "$ref_dir/../../../bd/system/ip/system_axis_subset_converter_0_13/hdl/tid_system_axis_subset_converter_0_13.v" \
    "$ref_dir/../../../bd/system/ip/system_axis_subset_converter_0_13/hdl/tdest_system_axis_subset_converter_0_13.v" \
    "$ref_dir/../../../bd/system/ip/system_axis_subset_converter_0_13/hdl/tlast_system_axis_subset_converter_0_13.v" \
    "$ref_dir/../../../bd/system/ip/system_axis_subset_converter_0_13/hdl/top_system_axis_subset_converter_0_13.v" \
    "$ref_dir/../../../bd/system/ip/system_axis_subset_converter_0_13/sim/system_axis_subset_converter_0_13.v" \
    "$ref_dir/../../../bd/system/ip/system_axis_subset_converter_3_0/hdl/tdata_system_axis_subset_converter_3_0.v" \
    "$ref_dir/../../../bd/system/ip/system_axis_subset_converter_3_0/hdl/tuser_system_axis_subset_converter_3_0.v" \
    "$ref_dir/../../../bd/system/ip/system_axis_subset_converter_3_0/hdl/tstrb_system_axis_subset_converter_3_0.v" \
    "$ref_dir/../../../bd/system/ip/system_axis_subset_converter_3_0/hdl/tkeep_system_axis_subset_converter_3_0.v" \
    "$ref_dir/../../../bd/system/ip/system_axis_subset_converter_3_0/hdl/tid_system_axis_subset_converter_3_0.v" \
    "$ref_dir/../../../bd/system/ip/system_axis_subset_converter_3_0/hdl/tdest_system_axis_subset_converter_3_0.v" \
    "$ref_dir/../../../bd/system/ip/system_axis_subset_converter_3_0/hdl/tlast_system_axis_subset_converter_3_0.v" \
    "$ref_dir/../../../bd/system/ip/system_axis_subset_converter_3_0/hdl/top_system_axis_subset_converter_3_0.v" \
    "$ref_dir/../../../bd/system/ip/system_axis_subset_converter_3_0/sim/system_axis_subset_converter_3_0.v" \
    "$ref_dir/../../../bd/system/sim/system.v" \
    "$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b973/hdl/verilog/AXIvideo2xfMat.v" \
    "$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b973/hdl/verilog/Block_Mat_exit51_pro.v" \
    "$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b973/hdl/verilog/CoreProcessDownArea.v" \
    "$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b973/hdl/verilog/fifo_w24_d1_A.v" \
    "$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b973/hdl/verilog/Inverse.v" \
    "$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b973/hdl/verilog/Inverse_xf_divisicud.v" \
    "$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b973/hdl/verilog/resize.v" \
    "$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b973/hdl/verilog/resize_accel.v" \
    "$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b973/hdl/verilog/resize_ip_AXILiteS_s_axi.v" \
    "$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b973/hdl/verilog/resize_ip_mac_mulfYi.v" \
    "$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b973/hdl/verilog/resize_ip_mac_mulg8j.v" \
    "$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b973/hdl/verilog/resize_ip_mac_mulibs.v" \
    "$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b973/hdl/verilog/resize_ip_mul_muleOg.v" \
    "$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b973/hdl/verilog/resize_ip_mul_mulhbi.v" \
    "$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b973/hdl/verilog/resize_ip_mux_83_dEe.v" \
    "$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b973/hdl/verilog/resize_ip_mux_813Hfu.v" \
    "$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b973/hdl/verilog/resize_ip_mux_833Gfk.v" \
    "$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b973/hdl/verilog/resize_ip_udiv_32bkb.v" \
    "$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b973/hdl/verilog/start_for_resize_IfE.v" \
    "$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b973/hdl/verilog/start_for_xfMat2AJfO.v" \
    "$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b973/hdl/verilog/xfExtractPixels.v" \
    "$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b973/hdl/verilog/xfMat2AXIvideo.v" \
    "$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b973/hdl/verilog/xFResizeAreaDownScal.v" \
    "$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b973/hdl/verilog/xFResizeAreaDownSjbC.v" \
    "$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b973/hdl/verilog/xFResizeAreaDownSkbM.v" \
    "$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b973/hdl/verilog/xFResizeAreaDownSocq.v" \
    "$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b973/hdl/verilog/xFResizeAreaDownSpcA.v" \
    "$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b973/hdl/verilog/xFResizeAreaDownSudo.v" \
    "$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b973/hdl/verilog/xFResizeAreaDownSwdI.v" \
    "$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b973/hdl/verilog/xFResizeAreaDownSxdS.v" \
    "$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b973/hdl/verilog/xFUdivResizeDownArea.v" \
    "$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b973/hdl/verilog/resize_ip.v" \
    "$ref_dir/../../../bd/system/ip/system_resize_ip_0_0/sim/system_resize_ip_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_protocol_converter_v2_1_17 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b65a" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/0ab1/hdl" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/ccfb/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b65a" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../video_overlay.srcs/sources_1/bd/system/ipshared/0ab1/hdl" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_auto_pc_0/sim/system_auto_pc_0.v" \
  2>&1 | tee -a vlogan.log

  g++ -c  -I "../../../../../../../xtlm/include" \
    "$ref_dir/../../../bd/system/ip/system_v_demosaic_0_0/src/v_demosaic.cpp" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.system xil_defaultlib.glbl -o system_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./system_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./system.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  lib_map_path=""
  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key system_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc system_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./system.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: system.sh [-help]\n\
Usage: system.sh [-lib_map_path]\n\
Usage: system.sh [-reset_run]\n\
Usage: system.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
