// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module Sobel (
        p_src_mat_rows_read,
        p_src_mat_cols_read,
        p_src_mat_data_V_dout,
        p_src_mat_data_V_empty_n,
        p_src_mat_data_V_read,
        p_dst_matx_rows_read,
        p_dst_matx_cols_read,
        p_dst_matx_data_V_din,
        p_dst_matx_data_V_full_n,
        p_dst_matx_data_V_write,
        p_dst_maty_cols_read,
        p_dst_maty_data_V_din,
        p_dst_maty_data_V_full_n,
        p_dst_maty_data_V_write,
        ap_clk,
        ap_rst,
        p_src_mat_rows_read_ap_vld,
        p_src_mat_cols_read_ap_vld,
        p_dst_matx_rows_read_ap_vld,
        p_dst_matx_cols_read_ap_vld,
        p_dst_maty_cols_read_ap_vld,
        ap_done,
        ap_start,
        ap_ready,
        ap_idle,
        ap_continue
);


input  [31:0] p_src_mat_rows_read;
input  [31:0] p_src_mat_cols_read;
input  [7:0] p_src_mat_data_V_dout;
input   p_src_mat_data_V_empty_n;
output   p_src_mat_data_V_read;
input  [31:0] p_dst_matx_rows_read;
input  [31:0] p_dst_matx_cols_read;
output  [7:0] p_dst_matx_data_V_din;
input   p_dst_matx_data_V_full_n;
output   p_dst_matx_data_V_write;
input  [31:0] p_dst_maty_cols_read;
output  [7:0] p_dst_maty_data_V_din;
input   p_dst_maty_data_V_full_n;
output   p_dst_maty_data_V_write;
input   ap_clk;
input   ap_rst;
input   p_src_mat_rows_read_ap_vld;
input   p_src_mat_cols_read_ap_vld;
input   p_dst_matx_rows_read_ap_vld;
input   p_dst_matx_cols_read_ap_vld;
input   p_dst_maty_cols_read_ap_vld;
output   ap_done;
input   ap_start;
output   ap_ready;
output   ap_idle;
input   ap_continue;

wire    Sobel_Loop_1_proc616_U0_ap_start;
wire    Sobel_Loop_1_proc616_U0_start_full_n;
wire    Sobel_Loop_1_proc616_U0_ap_done;
wire    Sobel_Loop_1_proc616_U0_ap_continue;
wire    Sobel_Loop_1_proc616_U0_ap_idle;
wire    Sobel_Loop_1_proc616_U0_ap_ready;
wire    Sobel_Loop_1_proc616_U0_start_out;
wire    Sobel_Loop_1_proc616_U0_start_write;
wire    Sobel_Loop_1_proc616_U0_p_src_mat_data_V_read;
wire   [7:0] Sobel_Loop_1_proc616_U0_p_src_V_V_din;
wire    Sobel_Loop_1_proc616_U0_p_src_V_V_write;
wire   [31:0] Sobel_Loop_1_proc616_U0_p_src_mat_rows_read_out_din;
wire    Sobel_Loop_1_proc616_U0_p_src_mat_rows_read_out_write;
wire   [31:0] Sobel_Loop_1_proc616_U0_p_src_mat_cols_read_out_din;
wire    Sobel_Loop_1_proc616_U0_p_src_mat_cols_read_out_write;
wire   [31:0] Sobel_Loop_1_proc616_U0_p_dst_matx_rows_read_out_din;
wire    Sobel_Loop_1_proc616_U0_p_dst_matx_rows_read_out_write;
wire   [31:0] Sobel_Loop_1_proc616_U0_p_dst_matx_cols_read_out_din;
wire    Sobel_Loop_1_proc616_U0_p_dst_matx_cols_read_out_write;
wire   [31:0] Sobel_Loop_1_proc616_U0_p_dst_maty_cols_read_out_din;
wire    Sobel_Loop_1_proc616_U0_p_dst_maty_cols_read_out_write;
wire    Sobel_Block_xFSobelF_U0_ap_start;
wire    Sobel_Block_xFSobelF_U0_ap_done;
wire    Sobel_Block_xFSobelF_U0_ap_continue;
wire    Sobel_Block_xFSobelF_U0_ap_idle;
wire    Sobel_Block_xFSobelF_U0_ap_ready;
wire    Sobel_Block_xFSobelF_U0_p_src_mat_rows_read_read;
wire    Sobel_Block_xFSobelF_U0_p_src_mat_cols_read_read;
wire    Sobel_Block_xFSobelF_U0_p_src_V_V_read;
wire   [7:0] Sobel_Block_xFSobelF_U0_p_dstx_V_V_din;
wire    Sobel_Block_xFSobelF_U0_p_dstx_V_V_write;
wire   [7:0] Sobel_Block_xFSobelF_U0_p_dsty_V_V_din;
wire    Sobel_Block_xFSobelF_U0_p_dsty_V_V_write;
wire    Sobel_Loop_2_proc62_U0_ap_start;
wire    Sobel_Loop_2_proc62_U0_ap_done;
wire    Sobel_Loop_2_proc62_U0_ap_continue;
wire    Sobel_Loop_2_proc62_U0_ap_idle;
wire    Sobel_Loop_2_proc62_U0_ap_ready;
wire    Sobel_Loop_2_proc62_U0_p_dst_matx_rows_read_read;
wire    Sobel_Loop_2_proc62_U0_p_dst_matx_cols_read_read;
wire    Sobel_Loop_2_proc62_U0_p_dstx_V_V_read;
wire   [7:0] Sobel_Loop_2_proc62_U0_p_dst_matx_data_V_din;
wire    Sobel_Loop_2_proc62_U0_p_dst_matx_data_V_write;
wire    Sobel_Loop_2_proc62_U0_p_dsty_V_V_read;
wire   [7:0] Sobel_Loop_2_proc62_U0_p_dst_maty_data_V_din;
wire    Sobel_Loop_2_proc62_U0_p_dst_maty_data_V_write;
wire    ap_sync_continue;
wire    p_src_V_V_full_n;
wire   [7:0] p_src_V_V_dout;
wire    p_src_V_V_empty_n;
wire    p_src_mat_rows_read_c_full_n;
wire   [31:0] p_src_mat_rows_read_c_dout;
wire    p_src_mat_rows_read_c_empty_n;
wire    p_src_mat_cols_read_c_full_n;
wire   [31:0] p_src_mat_cols_read_c_dout;
wire    p_src_mat_cols_read_c_empty_n;
wire    p_dst_matx_rows_read_s_full_n;
wire   [31:0] p_dst_matx_rows_read_s_dout;
wire    p_dst_matx_rows_read_s_empty_n;
wire    p_dst_matx_cols_read_s_full_n;
wire   [31:0] p_dst_matx_cols_read_s_dout;
wire    p_dst_matx_cols_read_s_empty_n;
wire    p_dstx_V_V_full_n;
wire   [7:0] p_dstx_V_V_dout;
wire    p_dstx_V_V_empty_n;
wire    p_dsty_V_V_full_n;
wire   [7:0] p_dsty_V_V_dout;
wire    p_dsty_V_V_empty_n;
wire    ap_sync_done;
wire    ap_sync_ready;
wire   [0:0] start_for_Sobel_Block_xFSobelF_U0_din;
wire    start_for_Sobel_Block_xFSobelF_U0_full_n;
wire   [0:0] start_for_Sobel_Block_xFSobelF_U0_dout;
wire    start_for_Sobel_Block_xFSobelF_U0_empty_n;
wire   [0:0] start_for_Sobel_Loop_2_proc62_U0_din;
wire    start_for_Sobel_Loop_2_proc62_U0_full_n;
wire   [0:0] start_for_Sobel_Loop_2_proc62_U0_dout;
wire    start_for_Sobel_Loop_2_proc62_U0_empty_n;
wire    Sobel_Block_xFSobelF_U0_start_full_n;
wire    Sobel_Block_xFSobelF_U0_start_write;
wire    Sobel_Loop_2_proc62_U0_start_full_n;
wire    Sobel_Loop_2_proc62_U0_start_write;

Sobel_Loop_1_proc616 Sobel_Loop_1_proc616_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(Sobel_Loop_1_proc616_U0_ap_start),
    .start_full_n(Sobel_Loop_1_proc616_U0_start_full_n),
    .ap_done(Sobel_Loop_1_proc616_U0_ap_done),
    .ap_continue(Sobel_Loop_1_proc616_U0_ap_continue),
    .ap_idle(Sobel_Loop_1_proc616_U0_ap_idle),
    .ap_ready(Sobel_Loop_1_proc616_U0_ap_ready),
    .start_out(Sobel_Loop_1_proc616_U0_start_out),
    .start_write(Sobel_Loop_1_proc616_U0_start_write),
    .p_src_mat_rows_read(p_src_mat_rows_read),
    .p_src_mat_cols_read(p_src_mat_cols_read),
    .p_src_mat_data_V_dout(p_src_mat_data_V_dout),
    .p_src_mat_data_V_empty_n(p_src_mat_data_V_empty_n),
    .p_src_mat_data_V_read(Sobel_Loop_1_proc616_U0_p_src_mat_data_V_read),
    .p_src_V_V_din(Sobel_Loop_1_proc616_U0_p_src_V_V_din),
    .p_src_V_V_full_n(p_src_V_V_full_n),
    .p_src_V_V_write(Sobel_Loop_1_proc616_U0_p_src_V_V_write),
    .p_dst_matx_rows_read(p_dst_matx_rows_read),
    .p_dst_matx_cols_read(p_dst_matx_cols_read),
    .p_dst_maty_cols_read(p_dst_maty_cols_read),
    .p_src_mat_rows_read_out_din(Sobel_Loop_1_proc616_U0_p_src_mat_rows_read_out_din),
    .p_src_mat_rows_read_out_full_n(p_src_mat_rows_read_c_full_n),
    .p_src_mat_rows_read_out_write(Sobel_Loop_1_proc616_U0_p_src_mat_rows_read_out_write),
    .p_src_mat_cols_read_out_din(Sobel_Loop_1_proc616_U0_p_src_mat_cols_read_out_din),
    .p_src_mat_cols_read_out_full_n(p_src_mat_cols_read_c_full_n),
    .p_src_mat_cols_read_out_write(Sobel_Loop_1_proc616_U0_p_src_mat_cols_read_out_write),
    .p_dst_matx_rows_read_out_din(Sobel_Loop_1_proc616_U0_p_dst_matx_rows_read_out_din),
    .p_dst_matx_rows_read_out_full_n(p_dst_matx_rows_read_s_full_n),
    .p_dst_matx_rows_read_out_write(Sobel_Loop_1_proc616_U0_p_dst_matx_rows_read_out_write),
    .p_dst_matx_cols_read_out_din(Sobel_Loop_1_proc616_U0_p_dst_matx_cols_read_out_din),
    .p_dst_matx_cols_read_out_full_n(p_dst_matx_cols_read_s_full_n),
    .p_dst_matx_cols_read_out_write(Sobel_Loop_1_proc616_U0_p_dst_matx_cols_read_out_write),
    .p_dst_maty_cols_read_out_din(Sobel_Loop_1_proc616_U0_p_dst_maty_cols_read_out_din),
    .p_dst_maty_cols_read_out_full_n(1'b1),
    .p_dst_maty_cols_read_out_write(Sobel_Loop_1_proc616_U0_p_dst_maty_cols_read_out_write)
);

Sobel_Block_xFSobelF Sobel_Block_xFSobelF_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(Sobel_Block_xFSobelF_U0_ap_start),
    .ap_done(Sobel_Block_xFSobelF_U0_ap_done),
    .ap_continue(Sobel_Block_xFSobelF_U0_ap_continue),
    .ap_idle(Sobel_Block_xFSobelF_U0_ap_idle),
    .ap_ready(Sobel_Block_xFSobelF_U0_ap_ready),
    .p_src_mat_rows_read_dout(p_src_mat_rows_read_c_dout),
    .p_src_mat_rows_read_empty_n(p_src_mat_rows_read_c_empty_n),
    .p_src_mat_rows_read_read(Sobel_Block_xFSobelF_U0_p_src_mat_rows_read_read),
    .p_src_mat_cols_read_dout(p_src_mat_cols_read_c_dout),
    .p_src_mat_cols_read_empty_n(p_src_mat_cols_read_c_empty_n),
    .p_src_mat_cols_read_read(Sobel_Block_xFSobelF_U0_p_src_mat_cols_read_read),
    .p_src_V_V_dout(p_src_V_V_dout),
    .p_src_V_V_empty_n(p_src_V_V_empty_n),
    .p_src_V_V_read(Sobel_Block_xFSobelF_U0_p_src_V_V_read),
    .p_dstx_V_V_din(Sobel_Block_xFSobelF_U0_p_dstx_V_V_din),
    .p_dstx_V_V_full_n(p_dstx_V_V_full_n),
    .p_dstx_V_V_write(Sobel_Block_xFSobelF_U0_p_dstx_V_V_write),
    .p_dsty_V_V_din(Sobel_Block_xFSobelF_U0_p_dsty_V_V_din),
    .p_dsty_V_V_full_n(p_dsty_V_V_full_n),
    .p_dsty_V_V_write(Sobel_Block_xFSobelF_U0_p_dsty_V_V_write)
);

Sobel_Loop_2_proc62 Sobel_Loop_2_proc62_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(Sobel_Loop_2_proc62_U0_ap_start),
    .ap_done(Sobel_Loop_2_proc62_U0_ap_done),
    .ap_continue(Sobel_Loop_2_proc62_U0_ap_continue),
    .ap_idle(Sobel_Loop_2_proc62_U0_ap_idle),
    .ap_ready(Sobel_Loop_2_proc62_U0_ap_ready),
    .p_dst_matx_rows_read_dout(p_dst_matx_rows_read_s_dout),
    .p_dst_matx_rows_read_empty_n(p_dst_matx_rows_read_s_empty_n),
    .p_dst_matx_rows_read_read(Sobel_Loop_2_proc62_U0_p_dst_matx_rows_read_read),
    .p_dst_matx_cols_read_dout(p_dst_matx_cols_read_s_dout),
    .p_dst_matx_cols_read_empty_n(p_dst_matx_cols_read_s_empty_n),
    .p_dst_matx_cols_read_read(Sobel_Loop_2_proc62_U0_p_dst_matx_cols_read_read),
    .p_dstx_V_V_dout(p_dstx_V_V_dout),
    .p_dstx_V_V_empty_n(p_dstx_V_V_empty_n),
    .p_dstx_V_V_read(Sobel_Loop_2_proc62_U0_p_dstx_V_V_read),
    .p_dst_matx_data_V_din(Sobel_Loop_2_proc62_U0_p_dst_matx_data_V_din),
    .p_dst_matx_data_V_full_n(p_dst_matx_data_V_full_n),
    .p_dst_matx_data_V_write(Sobel_Loop_2_proc62_U0_p_dst_matx_data_V_write),
    .p_dsty_V_V_dout(p_dsty_V_V_dout),
    .p_dsty_V_V_empty_n(p_dsty_V_V_empty_n),
    .p_dsty_V_V_read(Sobel_Loop_2_proc62_U0_p_dsty_V_V_read),
    .p_dst_maty_data_V_din(Sobel_Loop_2_proc62_U0_p_dst_maty_data_V_din),
    .p_dst_maty_data_V_full_n(p_dst_maty_data_V_full_n),
    .p_dst_maty_data_V_write(Sobel_Loop_2_proc62_U0_p_dst_maty_data_V_write)
);

fifo_w8_d2_A p_src_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Sobel_Loop_1_proc616_U0_p_src_V_V_din),
    .if_full_n(p_src_V_V_full_n),
    .if_write(Sobel_Loop_1_proc616_U0_p_src_V_V_write),
    .if_dout(p_src_V_V_dout),
    .if_empty_n(p_src_V_V_empty_n),
    .if_read(Sobel_Block_xFSobelF_U0_p_src_V_V_read)
);

fifo_w32_d2_A p_src_mat_rows_read_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Sobel_Loop_1_proc616_U0_p_src_mat_rows_read_out_din),
    .if_full_n(p_src_mat_rows_read_c_full_n),
    .if_write(Sobel_Loop_1_proc616_U0_p_src_mat_rows_read_out_write),
    .if_dout(p_src_mat_rows_read_c_dout),
    .if_empty_n(p_src_mat_rows_read_c_empty_n),
    .if_read(Sobel_Block_xFSobelF_U0_p_src_mat_rows_read_read)
);

fifo_w32_d2_A p_src_mat_cols_read_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Sobel_Loop_1_proc616_U0_p_src_mat_cols_read_out_din),
    .if_full_n(p_src_mat_cols_read_c_full_n),
    .if_write(Sobel_Loop_1_proc616_U0_p_src_mat_cols_read_out_write),
    .if_dout(p_src_mat_cols_read_c_dout),
    .if_empty_n(p_src_mat_cols_read_c_empty_n),
    .if_read(Sobel_Block_xFSobelF_U0_p_src_mat_cols_read_read)
);

fifo_w32_d3_A p_dst_matx_rows_read_s_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Sobel_Loop_1_proc616_U0_p_dst_matx_rows_read_out_din),
    .if_full_n(p_dst_matx_rows_read_s_full_n),
    .if_write(Sobel_Loop_1_proc616_U0_p_dst_matx_rows_read_out_write),
    .if_dout(p_dst_matx_rows_read_s_dout),
    .if_empty_n(p_dst_matx_rows_read_s_empty_n),
    .if_read(Sobel_Loop_2_proc62_U0_p_dst_matx_rows_read_read)
);

fifo_w32_d3_A p_dst_matx_cols_read_s_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Sobel_Loop_1_proc616_U0_p_dst_matx_cols_read_out_din),
    .if_full_n(p_dst_matx_cols_read_s_full_n),
    .if_write(Sobel_Loop_1_proc616_U0_p_dst_matx_cols_read_out_write),
    .if_dout(p_dst_matx_cols_read_s_dout),
    .if_empty_n(p_dst_matx_cols_read_s_empty_n),
    .if_read(Sobel_Loop_2_proc62_U0_p_dst_matx_cols_read_read)
);

fifo_w8_d2_A p_dstx_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Sobel_Block_xFSobelF_U0_p_dstx_V_V_din),
    .if_full_n(p_dstx_V_V_full_n),
    .if_write(Sobel_Block_xFSobelF_U0_p_dstx_V_V_write),
    .if_dout(p_dstx_V_V_dout),
    .if_empty_n(p_dstx_V_V_empty_n),
    .if_read(Sobel_Loop_2_proc62_U0_p_dstx_V_V_read)
);

fifo_w8_d2_A p_dsty_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Sobel_Block_xFSobelF_U0_p_dsty_V_V_din),
    .if_full_n(p_dsty_V_V_full_n),
    .if_write(Sobel_Block_xFSobelF_U0_p_dsty_V_V_write),
    .if_dout(p_dsty_V_V_dout),
    .if_empty_n(p_dsty_V_V_empty_n),
    .if_read(Sobel_Loop_2_proc62_U0_p_dsty_V_V_read)
);

start_for_Sobel_BfYi start_for_Sobel_BfYi_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_Sobel_Block_xFSobelF_U0_din),
    .if_full_n(start_for_Sobel_Block_xFSobelF_U0_full_n),
    .if_write(Sobel_Loop_1_proc616_U0_start_write),
    .if_dout(start_for_Sobel_Block_xFSobelF_U0_dout),
    .if_empty_n(start_for_Sobel_Block_xFSobelF_U0_empty_n),
    .if_read(Sobel_Block_xFSobelF_U0_ap_ready)
);

start_for_Sobel_Lg8j start_for_Sobel_Lg8j_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_Sobel_Loop_2_proc62_U0_din),
    .if_full_n(start_for_Sobel_Loop_2_proc62_U0_full_n),
    .if_write(Sobel_Loop_1_proc616_U0_start_write),
    .if_dout(start_for_Sobel_Loop_2_proc62_U0_dout),
    .if_empty_n(start_for_Sobel_Loop_2_proc62_U0_empty_n),
    .if_read(Sobel_Loop_2_proc62_U0_ap_ready)
);

assign Sobel_Block_xFSobelF_U0_ap_continue = 1'b1;

assign Sobel_Block_xFSobelF_U0_ap_start = start_for_Sobel_Block_xFSobelF_U0_empty_n;

assign Sobel_Block_xFSobelF_U0_start_full_n = 1'b1;

assign Sobel_Block_xFSobelF_U0_start_write = 1'b0;

assign Sobel_Loop_1_proc616_U0_ap_continue = 1'b1;

assign Sobel_Loop_1_proc616_U0_ap_start = ap_start;

assign Sobel_Loop_1_proc616_U0_start_full_n = (start_for_Sobel_Loop_2_proc62_U0_full_n & start_for_Sobel_Block_xFSobelF_U0_full_n);

assign Sobel_Loop_2_proc62_U0_ap_continue = ap_continue;

assign Sobel_Loop_2_proc62_U0_ap_start = start_for_Sobel_Loop_2_proc62_U0_empty_n;

assign Sobel_Loop_2_proc62_U0_start_full_n = 1'b1;

assign Sobel_Loop_2_proc62_U0_start_write = 1'b0;

assign ap_done = Sobel_Loop_2_proc62_U0_ap_done;

assign ap_idle = (Sobel_Loop_2_proc62_U0_ap_idle & Sobel_Loop_1_proc616_U0_ap_idle & Sobel_Block_xFSobelF_U0_ap_idle);

assign ap_ready = Sobel_Loop_1_proc616_U0_ap_ready;

assign ap_sync_continue = ap_continue;

assign ap_sync_done = Sobel_Loop_2_proc62_U0_ap_done;

assign ap_sync_ready = Sobel_Loop_1_proc616_U0_ap_ready;

assign p_dst_matx_data_V_din = Sobel_Loop_2_proc62_U0_p_dst_matx_data_V_din;

assign p_dst_matx_data_V_write = Sobel_Loop_2_proc62_U0_p_dst_matx_data_V_write;

assign p_dst_maty_data_V_din = Sobel_Loop_2_proc62_U0_p_dst_maty_data_V_din;

assign p_dst_maty_data_V_write = Sobel_Loop_2_proc62_U0_p_dst_maty_data_V_write;

assign p_src_mat_data_V_read = Sobel_Loop_1_proc616_U0_p_src_mat_data_V_read;

assign start_for_Sobel_Block_xFSobelF_U0_din = 1'b1;

assign start_for_Sobel_Loop_2_proc62_U0_din = 1'b1;

endmodule //Sobel
