// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module xFSobel3x3 (
        ap_ready,
        src_buf1_0_V_read,
        src_buf1_1_V_read,
        src_buf1_2_V_read,
        src_buf2_0_V_read,
        src_buf2_2_V_read,
        src_buf3_0_V_read,
        src_buf3_1_V_read,
        src_buf3_2_V_read,
        ap_return_0,
        ap_return_1
);


output   ap_ready;
input  [7:0] src_buf1_0_V_read;
input  [7:0] src_buf1_1_V_read;
input  [7:0] src_buf1_2_V_read;
input  [7:0] src_buf2_0_V_read;
input  [7:0] src_buf2_2_V_read;
input  [7:0] src_buf3_0_V_read;
input  [7:0] src_buf3_1_V_read;
input  [7:0] src_buf3_2_V_read;
output  [7:0] ap_return_0;
output  [7:0] ap_return_1;

wire    GradientvaluesX_V_wr_xFGradientX3x3_0_0_s_fu_72_ap_ready;
wire   [7:0] GradientvaluesX_V_wr_xFGradientX3x3_0_0_s_fu_72_ap_return;
wire    GradientvaluesY_V_wr_xFGradientY3x3_0_0_s_fu_88_ap_ready;
wire   [7:0] GradientvaluesY_V_wr_xFGradientY3x3_0_0_s_fu_88_ap_return;

xFGradientX3x3_0_0_s GradientvaluesX_V_wr_xFGradientX3x3_0_0_s_fu_72(
    .ap_ready(GradientvaluesX_V_wr_xFGradientX3x3_0_0_s_fu_72_ap_ready),
    .t0_V(src_buf1_0_V_read),
    .t2_V(src_buf1_2_V_read),
    .m0_V(src_buf2_0_V_read),
    .m2_V(src_buf2_2_V_read),
    .b0_V(src_buf3_0_V_read),
    .b2_V(src_buf3_2_V_read),
    .ap_return(GradientvaluesX_V_wr_xFGradientX3x3_0_0_s_fu_72_ap_return)
);

xFGradientY3x3_0_0_s GradientvaluesY_V_wr_xFGradientY3x3_0_0_s_fu_88(
    .ap_ready(GradientvaluesY_V_wr_xFGradientY3x3_0_0_s_fu_88_ap_ready),
    .t0_V(src_buf1_0_V_read),
    .t1_V(src_buf1_1_V_read),
    .t2_V(src_buf1_2_V_read),
    .b0_V(src_buf3_0_V_read),
    .b1_V(src_buf3_1_V_read),
    .b2_V(src_buf3_2_V_read),
    .ap_return(GradientvaluesY_V_wr_xFGradientY3x3_0_0_s_fu_88_ap_return)
);

assign ap_ready = 1'b1;

assign ap_return_0 = GradientvaluesX_V_wr_xFGradientX3x3_0_0_s_fu_72_ap_return;

assign ap_return_1 = GradientvaluesY_V_wr_xFGradientY3x3_0_0_s_fu_88_ap_return;

endmodule //xFSobel3x3
