-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.2
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity resize is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    p_src_rows_read : IN STD_LOGIC_VECTOR (31 downto 0);
    p_src_cols_read : IN STD_LOGIC_VECTOR (31 downto 0);
    p_src_data_V_dout : IN STD_LOGIC_VECTOR (23 downto 0);
    p_src_data_V_empty_n : IN STD_LOGIC;
    p_src_data_V_read : OUT STD_LOGIC;
    p_dst_rows_read : IN STD_LOGIC_VECTOR (31 downto 0);
    p_dst_cols_read : IN STD_LOGIC_VECTOR (31 downto 0);
    p_dst_data_V_din : OUT STD_LOGIC_VECTOR (23 downto 0);
    p_dst_data_V_full_n : IN STD_LOGIC;
    p_dst_data_V_write : OUT STD_LOGIC );
end;


architecture behav of resize is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal input_height_fu_94_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal input_height_reg_114 : STD_LOGIC_VECTOR (15 downto 0);
    signal input_width_fu_99_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal input_width_reg_119 : STD_LOGIC_VECTOR (15 downto 0);
    signal output_height_fu_104_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal output_height_reg_124 : STD_LOGIC_VECTOR (15 downto 0);
    signal output_width_fu_109_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal output_width_reg_129 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_xFResizeAreaDownScal_fu_78_ap_start : STD_LOGIC;
    signal grp_xFResizeAreaDownScal_fu_78_ap_done : STD_LOGIC;
    signal grp_xFResizeAreaDownScal_fu_78_ap_idle : STD_LOGIC;
    signal grp_xFResizeAreaDownScal_fu_78_ap_ready : STD_LOGIC;
    signal grp_xFResizeAreaDownScal_fu_78_stream_in_data_V_read : STD_LOGIC;
    signal grp_xFResizeAreaDownScal_fu_78_resize_out_data_V_din : STD_LOGIC_VECTOR (23 downto 0);
    signal grp_xFResizeAreaDownScal_fu_78_resize_out_data_V_write : STD_LOGIC;
    signal grp_xFResizeAreaDownScal_fu_78_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);

    component xFResizeAreaDownScal IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        stream_in_data_V_dout : IN STD_LOGIC_VECTOR (23 downto 0);
        stream_in_data_V_empty_n : IN STD_LOGIC;
        stream_in_data_V_read : OUT STD_LOGIC;
        resize_out_data_V_din : OUT STD_LOGIC_VECTOR (23 downto 0);
        resize_out_data_V_full_n : IN STD_LOGIC;
        resize_out_data_V_write : OUT STD_LOGIC;
        height : IN STD_LOGIC_VECTOR (15 downto 0);
        width : IN STD_LOGIC_VECTOR (15 downto 0);
        out_height : IN STD_LOGIC_VECTOR (15 downto 0);
        out_width : IN STD_LOGIC_VECTOR (15 downto 0) );
    end component;



begin
    grp_xFResizeAreaDownScal_fu_78 : component xFResizeAreaDownScal
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_xFResizeAreaDownScal_fu_78_ap_start,
        ap_done => grp_xFResizeAreaDownScal_fu_78_ap_done,
        ap_idle => grp_xFResizeAreaDownScal_fu_78_ap_idle,
        ap_ready => grp_xFResizeAreaDownScal_fu_78_ap_ready,
        stream_in_data_V_dout => p_src_data_V_dout,
        stream_in_data_V_empty_n => p_src_data_V_empty_n,
        stream_in_data_V_read => grp_xFResizeAreaDownScal_fu_78_stream_in_data_V_read,
        resize_out_data_V_din => grp_xFResizeAreaDownScal_fu_78_resize_out_data_V_din,
        resize_out_data_V_full_n => p_dst_data_V_full_n,
        resize_out_data_V_write => grp_xFResizeAreaDownScal_fu_78_resize_out_data_V_write,
        height => input_height_reg_114,
        width => input_width_reg_119,
        out_height => output_height_reg_124,
        out_width => output_width_reg_129);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_xFResizeAreaDownScal_fu_78_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_xFResizeAreaDownScal_fu_78_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    grp_xFResizeAreaDownScal_fu_78_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_xFResizeAreaDownScal_fu_78_ap_ready = ap_const_logic_1)) then 
                    grp_xFResizeAreaDownScal_fu_78_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                input_height_reg_114 <= input_height_fu_94_p1;
                input_width_reg_119 <= input_width_fu_99_p1;
                output_height_reg_124 <= output_height_fu_104_p1;
                output_width_reg_129 <= output_width_fu_109_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, grp_xFResizeAreaDownScal_fu_78_ap_done, ap_CS_fsm_state2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((grp_xFResizeAreaDownScal_fu_78_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, grp_xFResizeAreaDownScal_fu_78_ap_done, ap_CS_fsm_state2)
    begin
        if ((((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((grp_xFResizeAreaDownScal_fu_78_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(grp_xFResizeAreaDownScal_fu_78_ap_done, ap_CS_fsm_state2)
    begin
        if (((grp_xFResizeAreaDownScal_fu_78_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    grp_xFResizeAreaDownScal_fu_78_ap_start <= grp_xFResizeAreaDownScal_fu_78_ap_start_reg;
    input_height_fu_94_p1 <= p_src_rows_read(16 - 1 downto 0);
    input_width_fu_99_p1 <= p_src_cols_read(16 - 1 downto 0);
    output_height_fu_104_p1 <= p_dst_rows_read(16 - 1 downto 0);
    output_width_fu_109_p1 <= p_dst_cols_read(16 - 1 downto 0);
    p_dst_data_V_din <= grp_xFResizeAreaDownScal_fu_78_resize_out_data_V_din;

    p_dst_data_V_write_assign_proc : process(grp_xFResizeAreaDownScal_fu_78_resize_out_data_V_write, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            p_dst_data_V_write <= grp_xFResizeAreaDownScal_fu_78_resize_out_data_V_write;
        else 
            p_dst_data_V_write <= ap_const_logic_0;
        end if; 
    end process;


    p_src_data_V_read_assign_proc : process(grp_xFResizeAreaDownScal_fu_78_stream_in_data_V_read, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            p_src_data_V_read <= grp_xFResizeAreaDownScal_fu_78_stream_in_data_V_read;
        else 
            p_src_data_V_read <= ap_const_logic_0;
        end if; 
    end process;

end behav;
