// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef XSOBEL_IP_H
#define XSOBEL_IP_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xsobel_ip_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Axilites_BaseAddress;
} XSobel_ip_Config;
#endif

typedef struct {
    u32 Axilites_BaseAddress;
    u32 IsReady;
} XSobel_ip;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XSobel_ip_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XSobel_ip_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XSobel_ip_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XSobel_ip_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XSobel_ip_Initialize(XSobel_ip *InstancePtr, u16 DeviceId);
XSobel_ip_Config* XSobel_ip_LookupConfig(u16 DeviceId);
int XSobel_ip_CfgInitialize(XSobel_ip *InstancePtr, XSobel_ip_Config *ConfigPtr);
#else
int XSobel_ip_Initialize(XSobel_ip *InstancePtr, const char* InstanceName);
int XSobel_ip_Release(XSobel_ip *InstancePtr);
#endif

void XSobel_ip_Start(XSobel_ip *InstancePtr);
u32 XSobel_ip_IsDone(XSobel_ip *InstancePtr);
u32 XSobel_ip_IsIdle(XSobel_ip *InstancePtr);
u32 XSobel_ip_IsReady(XSobel_ip *InstancePtr);
void XSobel_ip_EnableAutoRestart(XSobel_ip *InstancePtr);
void XSobel_ip_DisableAutoRestart(XSobel_ip *InstancePtr);

void XSobel_ip_Set_height(XSobel_ip *InstancePtr, u32 Data);
u32 XSobel_ip_Get_height(XSobel_ip *InstancePtr);
void XSobel_ip_Set_width(XSobel_ip *InstancePtr, u32 Data);
u32 XSobel_ip_Get_width(XSobel_ip *InstancePtr);

void XSobel_ip_InterruptGlobalEnable(XSobel_ip *InstancePtr);
void XSobel_ip_InterruptGlobalDisable(XSobel_ip *InstancePtr);
void XSobel_ip_InterruptEnable(XSobel_ip *InstancePtr, u32 Mask);
void XSobel_ip_InterruptDisable(XSobel_ip *InstancePtr, u32 Mask);
void XSobel_ip_InterruptClear(XSobel_ip *InstancePtr, u32 Mask);
u32 XSobel_ip_InterruptGetEnabled(XSobel_ip *InstancePtr);
u32 XSobel_ip_InterruptGetStatus(XSobel_ip *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
