// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xinner_ctrl.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XInner_ctrl_CfgInitialize(XInner_ctrl *InstancePtr, XInner_ctrl_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Axilites_BaseAddress = ConfigPtr->Axilites_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XInner_ctrl_Start(XInner_ctrl *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XInner_ctrl_ReadReg(InstancePtr->Axilites_BaseAddress, XINNER_CTRL_AXILITES_ADDR_AP_CTRL) & 0x80;
    XInner_ctrl_WriteReg(InstancePtr->Axilites_BaseAddress, XINNER_CTRL_AXILITES_ADDR_AP_CTRL, Data | 0x01);
}

u32 XInner_ctrl_IsDone(XInner_ctrl *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XInner_ctrl_ReadReg(InstancePtr->Axilites_BaseAddress, XINNER_CTRL_AXILITES_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XInner_ctrl_IsIdle(XInner_ctrl *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XInner_ctrl_ReadReg(InstancePtr->Axilites_BaseAddress, XINNER_CTRL_AXILITES_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XInner_ctrl_IsReady(XInner_ctrl *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XInner_ctrl_ReadReg(InstancePtr->Axilites_BaseAddress, XINNER_CTRL_AXILITES_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XInner_ctrl_EnableAutoRestart(XInner_ctrl *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XInner_ctrl_WriteReg(InstancePtr->Axilites_BaseAddress, XINNER_CTRL_AXILITES_ADDR_AP_CTRL, 0x80);
}

void XInner_ctrl_DisableAutoRestart(XInner_ctrl *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XInner_ctrl_WriteReg(InstancePtr->Axilites_BaseAddress, XINNER_CTRL_AXILITES_ADDR_AP_CTRL, 0);
}

u32 XInner_ctrl_Get_input_V(XInner_ctrl *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XInner_ctrl_ReadReg(InstancePtr->Axilites_BaseAddress, XINNER_CTRL_AXILITES_ADDR_INPUT_V_DATA);
    return Data;
}

u32 XInner_ctrl_Get_input_V_vld(XInner_ctrl *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XInner_ctrl_ReadReg(InstancePtr->Axilites_BaseAddress, XINNER_CTRL_AXILITES_ADDR_INPUT_V_CTRL);
    return Data & 0x1;
}

void XInner_ctrl_Set_output_V(XInner_ctrl *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XInner_ctrl_WriteReg(InstancePtr->Axilites_BaseAddress, XINNER_CTRL_AXILITES_ADDR_OUTPUT_V_DATA, Data);
}

u32 XInner_ctrl_Get_output_V(XInner_ctrl *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XInner_ctrl_ReadReg(InstancePtr->Axilites_BaseAddress, XINNER_CTRL_AXILITES_ADDR_OUTPUT_V_DATA);
    return Data;
}

void XInner_ctrl_InterruptGlobalEnable(XInner_ctrl *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XInner_ctrl_WriteReg(InstancePtr->Axilites_BaseAddress, XINNER_CTRL_AXILITES_ADDR_GIE, 1);
}

void XInner_ctrl_InterruptGlobalDisable(XInner_ctrl *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XInner_ctrl_WriteReg(InstancePtr->Axilites_BaseAddress, XINNER_CTRL_AXILITES_ADDR_GIE, 0);
}

void XInner_ctrl_InterruptEnable(XInner_ctrl *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XInner_ctrl_ReadReg(InstancePtr->Axilites_BaseAddress, XINNER_CTRL_AXILITES_ADDR_IER);
    XInner_ctrl_WriteReg(InstancePtr->Axilites_BaseAddress, XINNER_CTRL_AXILITES_ADDR_IER, Register | Mask);
}

void XInner_ctrl_InterruptDisable(XInner_ctrl *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XInner_ctrl_ReadReg(InstancePtr->Axilites_BaseAddress, XINNER_CTRL_AXILITES_ADDR_IER);
    XInner_ctrl_WriteReg(InstancePtr->Axilites_BaseAddress, XINNER_CTRL_AXILITES_ADDR_IER, Register & (~Mask));
}

void XInner_ctrl_InterruptClear(XInner_ctrl *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XInner_ctrl_WriteReg(InstancePtr->Axilites_BaseAddress, XINNER_CTRL_AXILITES_ADDR_ISR, Mask);
}

u32 XInner_ctrl_InterruptGetEnabled(XInner_ctrl *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XInner_ctrl_ReadReg(InstancePtr->Axilites_BaseAddress, XINNER_CTRL_AXILITES_ADDR_IER);
}

u32 XInner_ctrl_InterruptGetStatus(XInner_ctrl *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XInner_ctrl_ReadReg(InstancePtr->Axilites_BaseAddress, XINNER_CTRL_AXILITES_ADDR_ISR);
}

